basic/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AddressForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * list all of the data stored
     * @return string
     */
    public function actionIndex() {
        $data = (new AddressForm())->listAll();

        yii::$app->view->params['addressBook'] = $data;

        return $this->render('index');
    }

    /**
     * display form for creating and item
     * @return string
     */
    public function actionNew() {
        return $this->render('create', [
            'model' => (new AddressForm()),
        ]);
    }

    /**
     * get item from database, if not item, display error
     * @return string
     */
    public function actionView() {
        $params = Yii::$app->request->getQueryParams();

        if (!isset($params['id'])) {
            return $this->render('error');
        }

        $data = (new AddressForm())->listOne((int)$params['id']);

        if (empty($data)) {
            Yii::$app->getSession()->setFlash('message', 'No data.');
            return $this->render('error');
        }

        yii::$app->view->params = $data;

        return $this->render('view', [
            'model' => (new AddressForm()),
        ]);
    }

    /**
     * validate and insert
     * @return string
     */
    public function actionAdd() {
        $model = new \app\models\AddressForm();

        if (!Yii::$app->request->post()) {
            return $this->goBack();
        }

        $params = Yii::$app->request->post();
        $model->attributes = $params['AddressForm'];

        if ($model->validate()) {
            (new AddressForm())->save($model->attributes);
            return $this->render('saved');
        }
        else {
            return $this->render('create', [
                'model' => $model,
                'errors' => $model->errors,
            ]);
        }
    }


    /**
     * validate and update
     * @return string
     */
/*
    public function actionUpdate() {
        if (!Yii::$app->request->post()) {
            return $this->goBack();
        }

        $params = Yii::$app->request->post();

        (new AddressForm())->update($params['AddressForm']);

        return $this->render('updated');
    }
*/

    public function actionUpdate() {
        $model = new \app\models\AddressForm();

        if (!Yii::$app->request->post()) {
            return $this->goBack();
        }

        $params = Yii::$app->request->post();
        $model->attributes = $params['AddressForm'];

        if ($model->validate()) {
            (new AddressForm())->update($params['AddressForm']);
            return $this->render('updated');
        }
        else {
            $data = [
                'id' => $params['AddressForm']['id'],
                'first_name' => $params['AddressForm']['fname'],
                'last_name' => $params['AddressForm']['lname'],
                'dob' => $params['AddressForm']['dob'],
                'zip' => $params['AddressForm']['zip'],
            ];

            yii::$app->view->params = $data;


            return $this->render('view', [
                'model' => $model,
                'errors' => $model->errors,
            ]);
        }
    }


    public function actionDelete() {
        $params = Yii::$app->request->getQueryParams();

        if (!isset($params['id'])) {
            return $this->render('error');
        }

        (new AddressForm())->deleteOne($params['id']);

        return $this->redirect('/',302);
    }
}

basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

basic/views/site/create.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Create';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('addressFormSubmitted')): ?>

        <div class="alert alert-success">
            Please enter the details below:
        </div>

    <?php else: ?>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['action' => '/site/add', 'id' => 'contact-form', 'options' => ['method' => 'post']]); ?>
                    <?= $form->field($model, 'fname')->label('First name:'); ?>
                    <?= $form->field($model, 'lname')->label('Last name:'); ?>
                    <?= $form->field($model, 'dob')->label('Date of Birth:')->textInput(['placeholder' => '12/14/2015']); ?>
                    <?= $form->field($model, 'zip')->label('Zip:'); ?>

                    <div class="form-group">
                        <?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'contact-button']); ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode(Yii::$app->session->getFlash('message'))) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

basic/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\bootstrap\Html;

$this->title = 'My Yii Application';
?>
<div class="site-index">
    <div class="body-content">
        <?php
        if (sizeof($this->params) == 0) :
            echo "<div class=\"alert alert-success\" role=\"alert\">You have no entries in your address book. Click the create button to get started: " . Html::a('Create +', ['/site/new'], ['class'=>'btn btn-primary']) . "</div>";

        else :
        ?>
        <div class="row col-lg-12">
            <?= Html::a('Create +', ['/site/new'], ['class'=>'btn btn-primary']) ?>
        </div>
        <div class="row col-lg-12">
            <table class="table">
                <tr>
                    <th>First</th>
                    <th>Last</th>
                    <th>D of B</th>
                    <th>Zip</th>
                    <th>&nbsp;</th>
                </tr>
                <?php
                foreach($this->params['addressBook'] as $item) {
                    echo "<tr>";
                    echo "<td>".(strlen($item['first_name']) ? Html::a($item['first_name'], ['/site/view/'.$item['id']]) : '&nbsp;')."</td>";
                    echo "<td>".(strlen($item['last_name']) ? $item['last_name'] : '&nbsp;')."</td>";
                    echo "<td>".(strlen($item['dob']) ? $item['dob'] : '&nbsp;')."</td>";
                    echo "<td>".(strlen($item['zip']) ? $item['zip'] : '&nbsp;')."</td>";
                    echo "<td>".Html::a('delete', ['/site/delete/'.$item['id']], ['class'=>'btn btn-danger btn-xs'])."</td>";
                    echo "</tr>";
                }
                ?>
            </table>
        </div>
        <div class="row col-lg-12">
            <?= Html::a('Create +', ['/site/new'], ['class'=>'btn btn-primary']) ?>
        </div>
        <?php endif; ?>
    </div>
</div>

basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

basic/views/site/saved.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Saved new contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php echo Html::a('Create +', ['/site/new'], ['class'=>'btn btn-primary']) ?>
</div>

basic/views/site/updated.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Updated contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php echo Html::a('Create +', ['/site/new'], ['class'=>'btn btn-primary']) ?>
</div>

basic/views/site/view.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Create';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('addressFormSubmitted')): ?>

        <div class="alert alert-success">
            Please enter the details below:
        </div>

    <?php else: ?>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['action' => '/site/update', 'id' => 'contact-form', 'options' => ['method' => 'post']]); ?>
                    <?= $form->field($model, 'id')->hiddenInput(['value'=>$this->params['id']])->label(false) ?>
                    <?= $form->field($model, 'fname')->label('First name:')->textInput(['value'=>$this->params['first_name']]) ?>
                    <?= $form->field($model, 'lname')->label('Last name:')->textInput(['value' => $this->params['last_name']]) ?>
                    <?= $form->field($model, 'dob')->label('Date of Birth:')->textInput(['placeholder' => '12/14/2015', 'value' => $this->params['dob']]) ?>
                    <?= $form->field($model, 'zip')->label('Zip:')->textInput(['value'=>$this->params['zip']]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>